export enum SongCategory {
  Rock = 'Rock',
  Pop = 'Pop',
  Jazz = 'Jazz',
  Country = 'Country',
  HipHop = 'Hip-Hop',
  RnB = 'R&B',
  Metal = 'Metal',
  Classical = 'Classical',
  Blues = 'Blues',
  Rockabilly = 'Rockabilly',
  Alternative = 'Alternative',
  Indie = 'Indie',
  RnBSoul = 'R&B/Soul',
  AlternativeRockabilly = 'Alternative/Rockabilly',
  BluesRockabilly = 'Blues/Rockabilly',
  HipHopRnB = 'Hip-Hop/R&B',
  HipHopRnBSoul = 'Hip-Hop/R&B/Soul',
  HipHopRnBSoulAlternative = 'Hip-Hop/R&B/Soul/Alternative',
  HipHopRnBSoulAlternativeRockabilly = 'Hip-Hop/R&B/Soul/Alternative/Rockabilly',
  HipHopRnBSoulAlternativeRockabillyBlues = 'Hip-Hop/R&B/Soul/Alternative/Rockabilly/Blues',
  HipHopRnBSoulAlternativeRockabillyBluesRockabilly = 'Hip-Hop/R&B/Soul/Alternative/Rockabilly/Blues/Rockabilly',
}
